### ISSUE TITLE
fix(journal-popover): the day selected is different that the day of the journal

### ISSUE THREAD

**Issue by mayramtv** [uol-student-life/student-life#112]
When creating a journal entry, the journal gets created the day before of the selected day.

![Image](https://github.com/uol-student-life/student-life/assets/81662672/8bad9d25-0821-499b-8524-ea80a68c1c57)

**Comment by claytonchew** [comment]
@mayramtv looks like a classic timezone issue

**Comment by mayramtv** [comment]
> @mayramtv looks like a classic timezone issue
> 
> Server receives the date in your timezone, but server receives your date and converts it to UTC time and strip off its time. It essentially:
> 
> 1. You send `2023-08-29T06:30:00.000+8:00`
> 2. Server receives it and proceed to convert to UTC `2023-08-28T20:30:00.000Z` (notice the `Z` meant UTC)
> 3. Then server strips its time to  `2023-08-28T00:00:00.000Z` (notice the time now resets 20 hours back)
> 4. Finally server stores it as a journal record with journal date `2023-08-28T00:00:00.000Z`
> 5. On fetch, your browser (which is in your timezone) reads `2023-08-28T00:00:00.000Z` and converts to your timezone which is `2023-08-28T08:00:00.000+8:00`. (hence you're seeing 1 day before)

Yes it was. It was very helpful. Thank you
